#!/bin/bash

echo "Hello everyone, we are collecting information about our commany's employees. Please, provide required info"
sleep 1

read -p "What is your first name? " name
echo 
read -p "What is your last name? " lastname
echo 

PS3="What type of phone do you prefer?: "
select phone in headset handheld ; 
do 
echo "Preferable phone: $phone"
break
done

echo 
PS3="Select your department?:  "
select department in  finance sales "customer service" engeineering ; 
do 
echo "Your department is: $department "
break
done

echo
read -N 4 -p "What is your extention number (it must be only 4 digits)? " extension
echo 
read -N 4 -s -p "What access code would you like to use when dialing in (it must be only 4 digits)? "  access
echo 
echo "Thank you, your information saved"
echo 

echo "$name,$lastname,$extension,$access,$phone,$department" >> extensions.csv  
