#!/bin/bash

echo "Hello, world"
echo "hello from $1"
echo "Hello there $2 $3 $4 "
echo "This is the line of allarguments given by the user: $@"
echo "This script is running with the PID: $$" 
echo "Test gpush command" 
